### PR TITLE
Decaffeinate

### PR DESCRIPTION
**Pull request by timothee-alby**
### Description

Decaffeinate the repo using the script added in https://github.com/overleaf/dev-environment/pull/290

Manual steps:
```bash
bin/update_build_scripts `< document-updater/buildscript.txt` --script-version=1.3.1
cd document-updater
git add .
git commit -m "update build scripts to 1.3.1"
cd ..
bin/decaffeinate.sh document-updater
cd document-updater
coffee -c test/cluster_failover/coffee/test_pubsub_failover.coffee
coffee -c test/cluster_failover/coffee/test_blpop_failover.coffee
g rm test/cluster_failover/coffee/*.coffee
g mv test/cluster_failover/coffee test/cluster_failover/js
npx prettier-eslint test/cluster_failover/js/**/*.js --write
git add .
git commit -m "decaffeinate: manually convert test/cluster_failover files"
cd ..
bin/update_build_scripts `< github-sync/buildscript.txt` --node-version=10.17.0
cd document-updater
git add .
git commit -m "update Node to 10.17.0"
```

#### Potential Impact

- the decaf is pretty low-impact: we've done it for other repos and it always went well
- the upgrade to Node 10 is a bit riskier but should be fine as well

### CODE REVIEW

**Comment by timothee-alby** [comment]
For this one the tests failed after the decaf. See the last commits for the fixes. It might be caused by a change to strict mode, bu that's odd and a bit worrying that the decaf didn't produce working code.

**Comment by briangough** [comment]
I'll need to finish the docupdater migration to a multiple redis backends before this can be merged so I've flagged the PR as blocked by https://github.com/overleaf/document-updater/pull/105.

**Comment by timothee-alby** [comment]
Sure, no hurry to get this merged, and we can run the script again if we have conflicts

**Comment by timothee-alby** [comment]
> Just want to check - the following are because the script didn't cover them or because decaffeinate failed with them?

Decaffeinate failed with them when used with `bulk-decaffeinate`. Using the coffee output is less pretty but at least it works.

>Do we want to separate this into separate changes: decaffeination and v10 upgrade?

My point was that it's easier to do both at once and we can monitor closely.

>Or alternatively I think they might be fine together with a canary deploy.

Yes good idea

**Comment by jdleesmiller** [comment]
> separate this into separate changes: decaffeination and v10 upgrade

This is an interesting one...

- Separate changes means less to go wrong in one upgrade, and it means that if something does go wrong, the scope of possible causes is narrowed.
- It does require more testing.
- That said, sometimes dependencies have problems that are related to the node version, so upgrading the dependencies is sometimes required and sometimes helpful.

For a core service like docupdater, I would say that it's worth moving slowly and carefully, so I would lean toward separating these changes.

**Comment by timothee-alby** [comment]
Sure thing. Removed the last commit.
Upgrade to Node 10 is still tracked in https://github.com/overleaf/issues/issues/1118

**Comment by briangough** [comment]
I definitely agree with doing the decaffeination and node upgrade separately.  

I feel like it would be safer to upgrade to node 10 first and then decaffeinate, because the upgrade to node 10 should not require any code changes. Docupdater is mostly just plain coffeescript (no streams or promises or anything like that) and only a few external dependencies (e.g. request) so I think a node upgrade should be safe.   We should only have memory/performance issues from a node upgrade.  I would prefer to sort those out with a known working codebase.

 For decaffeination, docupdater has some of the more complex logic in the stack (e.g  [RangesTracker.coffee](https://github.com/overleaf/document-updater/blob/ff2eed1a88ef137edb90a458ebda3f632d7d9bb2/app/coffee/RangesTracker.coffee)) and I think that makes it higher risk for decaffeination than the other services.

**Comment by 40thieves** [comment]
Can this be un-held now?

**Comment by ShaneKilkelly** [comment]
cc @timothee-alby , could we update this PR now that we've upgraded to node-10?

**Comment by jdleesmiller** [comment]
My understanding is that this is still waiting on project history migration to a new redis, not just node 10. So, waiting on Brian being more available (but may work with Eric).

image

**Comment by briangough** [comment]
This is unblocked now, the redis migration is complete.

**Comment by timothee-alby** [comment]
Great!
I started all over, rebasing onto `master`, updating the build scripts to `2.2.0` and running the decaf script.

I still had some manual work to do, and it's worth reviewing some of those commits carefully:
- disable linting for lib/diff_match_patch.js 2cafde2
- fix lint errors in config/settings.defaults.js e2945e8 ⚠️ 
- format config/settings.defaults.js & lib/diff_match_patch.js 3fe2073
- lint & format app.js c3b99ba ⚠️ 
- remove requires for coffee-script package in tests 97ca682
- fix Metrics module stub e75c51a
- fix SyntaxError on `export` var 972161c ⚠️

**Comment by timothee-alby** [comment]
Thanks, I'll remove those files 👍 

I'm going to wait for https://github.com/overleaf/document-updater/pull/125 to be merged by @mserranom and then redo the changes (running script + cherry-picking commits).

**Comment by ShaneKilkelly** [comment]
I think this is unblocked now.

**Pull request merged**
